CREATE TABLE [dbo].[GVCN1](
	[MaLop] [varchar](10) NOT NULL,
	[MaGV] [varchar](10) NOT NULL,
	[HK] [float] NOT NULL,
 CONSTRAINT [PK_GVCN1] PRIMARY KEY CLUSTERED 
(
	[MaLop] ASC,
	[MaGV] ASC,
	[HK] ASC
))
GO
ALTER TABLE [dbo].[GVCN1]  WITH CHECK ADD  CONSTRAINT [FK_GVCN1_GiaoVien] FOREIGN KEY([MaGV])
REFERENCES [dbo].[GiaoVien] ([MaGV])
GO
ALTER TABLE [dbo].[GVCN1] CHECK CONSTRAINT [FK_GVCN1_GiaoVien]
GO
ALTER TABLE [dbo].[GVCN1]  WITH CHECK ADD  CONSTRAINT [FK_GVCN1_Lop] FOREIGN KEY([MaLop])
REFERENCES [dbo].[Lop] ([MaLop])
GO
ALTER TABLE [dbo].[GVCN1] CHECK CONSTRAINT [FK_GVCN1_Lop]
GO


